package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
)

const defaultChartContent = `# mallcop chart — generated by mallcop init
# Edit to match your environment. See docs/charts.md for reference.

[identity]
name        = "mallcop-scan"
type        = "worker"
description = "One-shot security scan"

[[worksources]]
type = "schedule"

[budget]
max_tokens_per_session = 200000
max_tokens_per_task    = 50000

[autonomy]
max_tasks_per_session = 10

[capabilities]
gate_policy    = "gated"
authority      = ""   # set to your email
tool_allowlist = ["bash", "read", "grep", "glob"]

[lifecycle]
max_workers   = 1
time_limit    = "30m"
poll_interval = "60s"
`

func runInit(args []string) error {
	fs := flag.NewFlagSet("init", flag.ContinueOnError)
	dir := fs.String("dir", ".", "Directory to initialize")

	if err := fs.Parse(args); err != nil {
		return err
	}

	// Resolve absolute path.
	absDir, err := filepath.Abs(*dir)
	if err != nil {
		return fmt.Errorf("resolving dir: %w", err)
	}

	// Create directory if it doesn't exist.
	if err := os.MkdirAll(absDir, 0o755); err != nil {
		return fmt.Errorf("creating dir %s: %w", absDir, err)
	}

	chartsDir := filepath.Join(absDir, "charts")
	if err := os.MkdirAll(chartsDir, 0o755); err != nil {
		return fmt.Errorf("creating charts dir: %w", err)
	}

	chartFile := filepath.Join(chartsDir, "mallcop.toml")
	if _, err := os.Stat(chartFile); err == nil {
		fmt.Printf("mallcop init: chart already exists at %s — skipping\n", chartFile)
	} else {
		if err := os.WriteFile(chartFile, []byte(defaultChartContent), 0o644); err != nil {
			return fmt.Errorf("writing chart: %w", err)
		}
		fmt.Printf("mallcop init: created %s\n", chartFile)
	}

	outputDir := filepath.Join(absDir, "output")
	if err := os.MkdirAll(outputDir, 0o755); err != nil {
		return fmt.Errorf("creating output dir: %w", err)
	}
	fmt.Printf("mallcop init: created %s/\n", outputDir)

	fmt.Printf("\nNext steps:\n")
	fmt.Printf("  1. Edit %s — set your authority email and configure connectors\n", chartFile)
	fmt.Printf("  2. Run: mallcop scan --chart %s\n", chartFile)
	return nil
}
